// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (!kIsWeb) {
      throw UnsupportedError(
        'Cleanmate Rush is web-only. Run with Chrome or build with '
        '`flutter build web`.',
      );
    }
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKImw-z3NgJnBFyNRpmLz-9Gf5Rwocen0',
    appId: '1:24458999176:web:f4e9bea6aa490fb0ec363d',
    messagingSenderId: '24458999176',
    projectId: 'cleanmate-f0088',
    authDomain: 'cleanmate-f0088.firebaseapp.com',
    storageBucket: 'cleanmate-f0088.firebasestorage.app',
    measurementId: 'G-B6FMEYB3LG',
  );
}
